# Continuous Integration
# Version Control
#    - name: Git
#      block:
#        - name: Install Git
#          yum: name=git state=latest

# CI Server
#    - name: Jenkins
#      block:
#        - name: Download Jenkins Yum Repository Definition
#          get_url: dest=/etc/yum.repos.d/jenkins.repo url=https://pkg.jenkins.io/redhat-stable/jenkins.repo
#        - name: Add Jenkins GPG Key To RPM Database
#          command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
#        - name: Install Jenkins
#          yum: name=jenkins state=latest
#        - name: Enable & Start Jenkins
#          systemd: name=jenkins enabled=true state=started
#        - name: Please Manually Activate Jenkins
#          debug: msg="Copy the code from /var/lib/jenkins/secrets/initialAdminPassword into http://localhost:8080."
#        - name: Set JENKINS_HOME Environment Variabler
#          lineinfile: path=~/.bashrc  line="JENKINS_HOME=/var/lib/jenkins insertafter=EOF state=present


# Documentation
    - name: Sphinx
      block:
        - name: Install Sphinx (Documentation)
          pip: name=sphinx state=latest executable=pip3

# Inspection
    - name: PyLint
      block:
        - name: Install Pylink
          pip: name=pylint state=latest executable=pip3

