#    - name: Mongodb
#      block:
#        - name: Setup Mongodb Yum Repository
#          blockinfile:
#            create: yes
#            block: |
#              [mongodb-org-3.4]
#              name=MongoDB Repository
#              baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
#              gpgcheck=1
#              enabled=1
#              gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc
#            dest: /etc/yum.repos.d/mongodb-org-3.4.repo
#        - name: Install Mongodb
#          yum: name=mongodb-org state=latest
#        - name: Setting Mongodb Data Path To Something More Suitable & Secure
#        - name: Create Mongodb Data Directory
#          file: path=/data/db state=directory mode="a+rwx"
